---
acmeCustomDnsServers:
  - 8.8.8.8
  - 8.8.4.4
acmeDnsProvider: route53

domains:
  - domain: nas.ez.soeren.cloud
    sans:
      - nas.ha.soeren.cloud
  - domain: nas.dd.soeren.cloud
    sans:
      - nas.ha.soeren.cloud
      - jelly.ha.soeren.cloud
  - domain: nas.pt.soeren.cloud
    sans:
      - nas.ha.soeren.cloud
      - jelly.ha.soeren.cloud
  - domain: dbs.ez.soeren.cloud
    sans:
      - minio-2.soeren.cloud
      - dbs.ha.soeren.cloud
  - domain: dbs.dd.soeren.cloud
    sans:
      - minio-1.soeren.cloud
      - dbs.ha.soeren.cloud
  - domain: dbs.pt.soeren.cloud
    sans:
      - minio-3.soeren.cloud
      - dbs.ha.soeren.cloud
  - domain: hass.dd.soeren.cloud
  - domain: mqtt.ez.soeren.cloud
  - domain: mqtt.dd.soeren.cloud
  - domain: mqtt.pt.soeren.cloud
  - domain: pim.dd.soeren.cloud
    sans:
      - pim-sandbox.soeren.cloud
  - domain: sauron.ez.soeren.cloud
  - domain: sauron.dd.soeren.cloud
  - domain: sauron.pt.soeren.cloud
  - domain: pool.pt.soeren.cloud
  - domain: brick.dd.soeren.cloud
  - domain: pool.ez.soeren.cloud
    sans:
      - paperless.ez.soeren.cloud
      - paperless.soeren.cloud

email: acmevault@soerensoerensen.de

metricsAddr: ""

vault:
  addr: https://vault.ha.soeren.cloud:443
  authMethod: implicit
  pathPrefix: prod
  k8sRoleId: acmevault
  k8sMountPath: svc.pt.soeren.cloud
