---
name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0

      - uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.21'

      - name: build binary
        run: make build

      - name: run all tests
        run: make tests