---
name: Tests and build

on:
  push:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0

      - uses: actions/setup-go@v4.0.1
        with:
          go-version: '1.20'

      - name: build binary
        run: make build

      - name: run all tests
        run: make tests
